name: Shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: echo string
        run: echo "hello world"
      
      - name: multi string
        run: |
          node -v
          npm -v

      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windows-command:
    runs-on: windows-latest
    needs : ["run-shell-commands"]
    steps:
      - name: Directory
        run: Get-Location

      - name: directory bash
        run: pwd
        shell: bash

